name: gcp_artifact_repository_dart
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  shelf: ^1.4.2 # REST API server framework
  shelf_router: ^1.1.2 # Routing for shelf
  googleapis: ^15.0.0 # Google APIs client library (accessing Artifact Registry)
  googleapis_auth: ^2.0.0 # Authentication for Google APIs
  logging: ^1.3.0 # Logs
  http: ^1.5.0 # HTTP client
  yaml: ^3.1.3 # YAML parsing
  crypto: ^3.0.6 # Package version hashing
  archive: ^4.0.7 # Reading .tar.gz files

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
